name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Use Gradle Wrapper if it exists
      - name: Check Gradle Wrapper Exists
        id: check-wrapper
        run: |
          if [ -f ./gradlew ]; then
            echo "wrapper-exists=true" >> $GITHUB_ENV
          else
            echo "wrapper-exists=false" >> $GITHUB_ENV
          fi

      - name: Build with Gradle Wrapper
        if: env.wrapper-exists == 'true'
        run: ./gradlew build

      # Fallback to a specified Gradle version if the wrapper does not exist
      - name: Setup Gradle
        if: env.wrapper-exists == 'false'
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Build with Specific Gradle Version
        if: env.wrapper-exists == 'false'
        run: gradle build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v3
        with:
          name: Residence
          path: build/libs/*.jar

      - name: Generate and Submit Dependency Graph
        uses: gradle/actions/dependency-submission@v4
