name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Ensure Gradle wrapper is executable
      - name: Ensure Gradle Wrapper Permissions
        run: chmod +x gradlew
        continue-on-error: true

      # Run Gradle build using the wrapper
      - name: Build with Gradle Wrapper
        run: ./gradlew build
        continue-on-error: true

      # If the Gradle wrapper is not available, fallback to a specific Gradle version
      - name: Fallback to Specific Gradle Version
        if: failure()
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Build with Specific Gradle Version
        if: failure()
        run: gradle build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v3
        with:
          name: Residence
          path: build/libs/*.jar

      - name: Generate and Submit Dependency Graph
        uses: gradle/actions/dependency-submission@v4
